arm64: efi: Switch to static_assert wrapper
The backported commit 96bc083042d87f305e144ce89aad897f8bd687d4 switched
static_assert to _Static_assert compared to the upstream commit, which
causes the following error when building with -Werror:

arch/arm64/kernel/efi.c:157:36: error: '_Static_assert' with no message
is a C2x extension [-Werror,-Wc2x-extensions]
_Static_assert(THREAD_SIZE >= SZ_8K);
                                   ^
                                   , ""
1 error generated.

Switch back to static_assert after picking the required upstream commit
6bab69c65013bed5fce9f101a64a84d0385b3946
"build_bug.h: add wrapper for _Static_assert"

Fixes: 96bc083042d8 ("BACKPORT: arm64: efi: Execute runtime services
       from a dedicated stack")
Signed-off-by: Michael Bestas <mkbestas@lineageos.org>
Change-Id: I74ff73517c49792d73f9bd4189ef73aec6addee0